type Query {
  allClusters: [Cluster!]!
  defaultCluster: Cluster
  clusterByRef(ref: String!): Cluster

  allProjects: [Project!]!
  projectById(id: String!): Project

  allWorkspaces: [Workspace!]!
  workspaceById(id: String!): Workspace
  workspaceByRef(ref: String!): Workspace

  allStacks: [Stack!]!
  stackById(id: String!): Stack
  stackByRef(ref: String!): Stack

  componentById(id: String!): Component
  componentByRef(ref: String!, stack: String): Component

  allResources: [Resource!]! # TODO: Paginate!
  resourceById(id: String!): Resource
  resourceByRef(ref: String!): Resource
  
  tasksByJobId(jobId: String!): [Task!]!
}

type Mutation {
  stopDaemon(): Void

  createProject(displayName: String): Project!
  
  createWorkspace(root: String!, projectID: String): Workspace!
  setWorkspaceStack(workspace: String!, stack: String): Stack

  buildWorkspace(workspace: String!): Void
  refreshWorkspace(workspace: String!): Void
  startWorkspace(workspace: String!): Void
  restartWorkspace(workspace: String!): Void
  stopWorkspace(workspace: String!): Void

  buildWorkspaceComponents(workspace: String!, components: [String!]!): Void
  refreshWorkspaceComponents(workspace: String!, components: [String!]!): Void
  startWorkspaceComponents(workspace: String!, components: [String!]!): Void
  stopWorkspaceComponents(workspace: String!, components: [String!]!): Void
  restartWorkspaceComponents(workspace: String!, components: [String!]!): Void

  createResource(type: String!, model: String!, ownerType: String, workspace: String, component: String, adopt: Boolean): Resource!
  forgetResource(ref: String!): Void
  cancelResourceOperation(ref: String!): Resource!

  # These operations must be called asynchronously.
  # They take an exclusive lock on the resource.
  initializeResource(ref: String!, model: String!): Void
  refreshResource(ref: String!): Resource!
  updateResource(ref: String!, model: String!): Resource!
  disposeResource(ref: String!): Void

  createTask(parentId: String, mutation: String!, arguments: String!): Task!
  acquireTask(workerId: String!, jobId: String, timeout: Int): Task
  startTask(id: String!, workerId: String!): Task!
  updateTask(id: String!, workerId: String!, message: String, progress: ProgressInput): Task!
  finishTask(id: String!, error: String): Void
  cancelJob(id: String!): Void

  createStack(cluster: String, workspace: String, name: String): Stack!

  createComponent(stack: String!, name: String! type: String! spec: String!): Reconciliation!
  reconcileComponent(stack: String, ref: String!): Reconciliation!
  updateComponent(stack: String, ref: String!, spec: String!): Reconciliation!
  disposeComponent(stack: String, ref: String!): Reconciliation!

  # For testing.
  sleep(seconds: Float!): Void
}

# ISO-8601 timestamp in UTC.
scalar Instant

type Void {}

type Cluster {
  id: String!
  name: String!
  default: Boolean!
}

type Project {
  id: String!
  displayName: String

  stacks: [Stack!]!

  resources: [Resource!]!
}

type Workspace {
  id: String!
  root: String!
  fileSystem: FileSystem!

  projectID: String!
  project: Project!

  stackId: String
  stack: Stack

  environment: Environment!

  components: [Component!]!
  resources: [Resource!]!
}

type Stack {
  id: String!
  name: String!

  clusterID: String!
  cluster: Cluster!

  projectID: String
  project: Project

  workspaceID: String
  workspace: Workspace

  components: [Component!]!
  resources: [Resource!]!
}

type Component {
  id: String!

  stackId: String!
  stack: Stack!

  type: String!
  name: String!

  resources: [Resource!]!
}

type Reconciliation {
  component: Component!
  job: Task!
}

type Environment {
  variables: [Variable!]!
}

type Variable {
  name: String!
  value: String!
  source: String!
}

type Resource {
  id: String!
  type: String!

  iri: String

  owner: ResourceOwner
  ownerType: String
  ownerId: String

  # Owner, if it is a project. Or the stack's project.
  project: Project
  # Owner, if it is a stack. Or the component's stack.
  stack: Stack
  # Owner, if it is a component.
  component: Component
  
  # If non-null, job has a lock on resource and state will not be "idle".
  jobId: String
  job: Task
  operation: String # creating, adopting, refreshing, updating, or disposing.

  model: String!

  # HTTP error code from previous finished task.
  status: Int!
  # Error message from previous finished task.
  message: String
}

union ResourceOwner = Component | Stack | Project

type FileSystem {
  file(path: String!): File
}

type File {
  name: String!
  path: String!
  isDirectory: Boolean!
  size: Float!
  content: String!
  children: [File!]!
}

type Task {
  id: String!
  jobId: String!
  job: Task!
  parentId: String
  mutation: String!
  arguments: String!
  parent: Task
  label: String!
  workerId: String
  status: String!
  created: Instant!
  updated: Instant!
  started: Instant
  canceled: Instant
  finished: Instant
  progress: Progress
  message: String
}

type Progress {
  current: Int!
  total: Int!
  percent: Float!
}

input ProgressInput {
  current: Int!
  total: Int!
}
