#!/usr/bin/env bash
set -euo pipefail

source "$( dirname "${BASH_SOURCE[0]}" )/.include"

# dexo stands for "development exo". It's just a script meant to replace "go
# run ./cmd/exo" in development. It builds the version of exo on HEAD and
# configures the client to talk to the development instance of exo and can be
# run from any working directory.

pushd "$ROOT_DIR" > /dev/null

tmp_dir=$(mktemp -d -t tmp-dexo-XXXXXXX)
trap 'rm -rf -- "$tmp_dir"' EXIT

go build -o "$tmp_dir" ./cmd/exo

popd > /dev/null
EXO_HOME="$EXO_DEV_HOME" "$tmp_dir/exo" "$@"
