#!/usr/bin/env bash
set -euo pipefail

source "$( dirname "${BASH_SOURCE[0]}" )/.include"

# dexo stands for "development exo". It's just a script meant to replace "go
# run ./cmd/exo" in development. It builds the version of exo on HEAD and
# configures the client to talk to the development instance of exo and can be
# run from any working directory.

(
  cd "$ROOT_DIR"
  go build -o "$EXO_DEV_HOME/bin/exo" ./cmd/exo
)

export EXO_HOME="$EXO_DEV_HOME"

"$EXO_DEV_HOME/bin/exo" "$@"
